export const MEDICINE_CATEGORIES = [
    "Antibiotics",
    "Antivirals",
    "Antifungals",
    "Antiparasitics / Antihelminthics / Antimalarials",
    "Analgesics (painkillers)",
    "Antipyretics (fever reducers)",
    "Anti-inflammatories (NSAIDs, steroids)",
    "Antacids",
    "Anti-ulcer drugs (PPIs, H2 blockers)",
    "Antihistamines",
    "Decongestants",
    "Cough medicines (expectorants, antitussives)",
    "Antiemetics",
    "Antidiarrhoeals",
    "Laxatives",
    "Antidiabetics",
    "Antihypertensives",
    "Antianginal drugs",
    "Antiarrhythmics",
    "Diuretics",
    "Lipid-lowering drugs (statins etc.)",
    "Anticoagulants",
    "Antiplatelets",
    "Bronchodilators",
    "Inhaled corticosteroids",
    "Antidepressants",
    "Antipsychotics",
    "Mood stabilizers",
    "Anxiolytics (anti-anxiety)",
    "Sedatives / Hypnotics",
    "Antiepileptics",
    "Hormonal medicines (thyroid, contraceptives, steroids, etc.)",
    "Osteoporosis / bone medicines",
    "Ophthalmic medicines (eye drops)",
    "Dermatological medicines (creams/ointments)",
    "Vitamins",
    "Minerals",
    "Nutritional supplements"
] as const;

export const DOCTOR_SPECIALIZATIONS = [
    "General Practitioner / Family Physician",
    "General Medicine (Physician / Internal Medicine)",
    "General Surgeon",
    "Paediatrician",
    "Obstetrician & Gynaecologist (OB/GYN)",
    "Cardiologist",
    "Neurologist",
    "Endocrinologist",
    "Nephrologist",
    "Gastroenterologist",
    "Respiratory Physician",
    "Rheumatologist",
    "Dermatologist",
    "Psychiatrist",
    "Oncologist",
    "Radiologist",
    "Anaesthetist / Anaesthesiologist",
    "Emergency Medicine Specialist",
    "Orthopaedic Surgeon",
    "ENT Surgeon (Otorhinolaryngologist)",
    "Eye Surgeon / Ophthalmologist",
    "Paediatric Surgeon",
    "Oral & Maxillofacial Surgeon",
    "Urologist",
    "Community Physician / Community Medicine",
    "Pathologist / Histopathologist",
    "Microbiologist",
    "Virologist",
    "Parasitologist",
    "Chemical Pathologist"
] as const;
